### PR TITLE
NPM & Paths to example

### PR DESCRIPTION
**Pull request by headwinds**
I looked at the readme on NPM and noticed that the nice animated gif is broken so I provided an absolute link to it (thanks stackoverflow) and then changed a broken link to the example site.

What tool did you use to create that gif? It's a bit crunched... in the future we should create a cleaner, more high rez version but this is fine for now - I'm sure you did it for speed to download

### CODE REVIEW

**Comment by bencripps** [comment]
For commits to grid, I'll always recommend that simple MR's (like this one) be squashed into a single commit, here's an [excerpt](https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits?course=how-to-contribute-to-an-open-source-project-on-github) that explains this process.  

> Often, project maintainers prefer that a single pull request be represented by a single commit. It makes the git history cleaner and easier to understand. So before your pull request is merged you’ll want to do an interactive git rebase to squash all of your commits and fix your commit message. 

It would be also cool to change all of the links in the README for external documents, like those in the `docs` folder, since they are not absolutely linked either.

This is a [guide](https://gist.github.com/dergachev/4627207) for making GIFS -- if you'd like you can play around with variables to see if you can get a cleaner version. You are correct though, the file size is an issue, and 2.73MB (the current size) is the smallest I could get with reasonable fidelity.

**Comment by bencripps** [comment]
Also just noticed now, that most of this work was already complete on master except for the fixes to two of the examples.

**Comment by headwinds** [comment]
Sorry I'll try to remember to do a squash comments - bad habit. Only updated links in 3 places so I'm probably merging incorrectly - it shouldn't appear that I've duplicated work - weird.

2.7MB gif is a big; too big; instead of auto play - I wonder if a static image would better with a play button that loads the animated version; then users have the choice and speed

I'll take a look at the links in the doc - yes it would be better if they didn't break; could be auto generated

**Comment by headwinds** [comment]
I wonder if we can enforce a git commit policy? Perhaps, use custom code like is mentioned [here] and (https://github.com/Freeseer/freeseer/issues/244) [here](https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy)?! For future devs like me... ;-D have a git hook that rejects commits that don't have a single atomic comment with this code

**Comment by bencripps** [comment]
I don't think it needs to be automated but that's a good idea. There is documentation in the grid repo that provides guidelines for making PR's. I think that will suffice for now.

**Comment by headwinds** [comment]
Ok works for me - I'll fix my commit message

**Pull request closed without merging**
