### PR TITLE
add event callback when table sort changes

### PR DESCRIPTION
**Pull request by rwilcox**
Howdy!

This is a pretty neat React component! It's saved me a fair bit of time.

One thing I do need it to do is to send me an event when the table sort changes. (I need to keep track of what/where the current sorting is in my parent component).

Let me know if there's anything I need to change to get this accepted.

### CODE REVIEW

**Comment by bencripps** [comment]
I need to update the readme, but there is already an event associated with sorts. The event is called `HANDLE_BEFORE_SORT`, and is passed in through the `events` object. Does this satisfy your requirements? If not, we can add a `HANDLE_AFTER_SORT` event, but I'm not sure it's entirely useful.

Let me know your thoughts, and thanks for the pull request!

**Comment by rwilcox** [comment]
Hmmm. I didn't see `HANDLE_BEFORE_SORT`, and yes this does seem to handle my needs (it passes in the column sorted on). I'll take a run at it and see...

**Comment by bencripps** [comment]
This issue was brought up in #49 

Suggest we close unless this event doesn't entirely satisfy your use case.

**Comment by rwilcox** [comment]
Tested it now - that does work, thanks.

(Although if you could document that mention that would be nice ;) )

**Comment by bencripps** [comment]
I will add the event to the documentation this morning. Thanks!

**Pull request closed without merging**
