### PR TITLE
new tests (PagerActios, throttle checkbox) & README reference links for NPM

### PR DESCRIPTION
**Pull request by headwinds**
first off, I'll apologize for my last commit - total mess - now I think I've finally got the hang of rebasing to ensure my master is in sync with your upstream master then rebasing my working branch on top of that

So now you should only see my new changes - this time I also took extra time to actually check the differences which I forgot do on the last push and will do so in the future.  

The major changes include:
- added atomic guideline to contribution doc
- readme now has reference links to docs at the bottom to support absolute URLs
- added new tests bringing coverage to over 80%

I was thinking about other ways to enforce git commits... then I realized what I want is a bot! I just need a simple reminder... maybe one of these: 

[thoughtbot](https://robots.thoughtbot.com/autosquashing-git-commits)
[cadencebot](https://cadencebot.com/)
[gitbot](http://gitbot.co)

### CODE REVIEW

**Comment by bencripps** [comment]
Awesome, this looks much better!

I think we probably don't want to link to the `raw` files since we lose all the markdown formatting -- rather we could use these URL's: 

Contributing: https://github.com/bencripps/react-redux-grid/blob/master/docs/CONTRIBUTING.MD

Would you mind changing them to these absolute references?

Also, since your updating the CONTRIBUTING.MD file, would you mind changing it to the following

https://hastebin.com/epimuzajiq.coffeescript

**Comment by bencripps** [comment]
Changes look good, I'll merge after the squash.

**Comment by headwinds** [comment]
Ahh ok I didn't think this time it deserved a squash since it's a new commit with an update referring different work done but I'll squash it down again - so until the owner accepts it - it's considered the same commit

**Comment by headwinds** [comment]
that should do it - definitely less painful than writing tests for throttle.js ;-D

**Pull request merged**
