### PR TITLE
Feature/editor select

### PR DESCRIPTION
**Pull request by kkwak**
Not sure if this is useful.. but I needed a select editor.. and wrapping the function everywhere wasn't nice.

I did notice that it broke component/plugins/editor/Inline.jsx
(but it breaks for anything other than an <input />)

`
export const resetEditorPosition = (editorState, store, stateKey) => {
   const input = document.querySelector(
          '.react-grid-edit .react-grid-editor-wrapper input:enabled'
      );
...
};
 
   export const resetEditorPosition = (editorState, store, stateKey) => {
     const input = document.querySelector(
        '.react-grid-edit .react-grid-editor-wrapper input:enabled'
     );
...
};
`
Seems this requires an "input" which obvious doesn't work for non-inputs
pick and choose the commits if they work.. I also added a local grid in the example.

### CODE REVIEW

**Comment by bencripps** [comment]
First, thanks for the pull request! I've looked over the changes and I have a couple of comments:

### Feature/editor-select

1. I don't know that complex `editors` should be part of the source code. We're using many grid implementations in an app, and our editors thus far have been part of that app's source code. Although the select isn't super complex, it solves a specific use case that isn't generic to the problem we're trying to solve with grid. That being said, I really like how you implemented the change -- simply designating the editor value as an array is elegant. I'm open to accepting a subset of simple editors such as select, or checkbox, and so on. But I think the location of this file should be `src/components/layout/table-row/row/cell/editors/Select.jsx`; that way, we could group all editors in that folder. Furthermore, if we're going to start adding editors to the grid source, we may want to think about the api for designating editors; 

````js
{
    name: 'Gender',
    dataIndex: 'gender',
    editor: {
        type: 'select',
        values: [
            {
                value: 'male',
                display: 'Male'
            },
            {
                value: 'female',
                display: 'Female'
            }
        ]
    }
};
````

We could expand the type to include new editors, but it could also be a function that renders a custom editor. As you can see from the above altered api for select, these things can get very complex.


### General

2. There is an `editorconfig` and a linter that are established in the grid source -- it doesn't look like the linter is working in your editor. There are many linting issues in your changes that I would like to see resolved before any merge could happen. You can also run `npm run lint` to see all linting issues. 

3. I love what you've done with the demo file. I think rather than having many grids on the same page, we might want to have multiple `html` files titled `local`, `remote`, `paginated`, and so on. This should probably also submitted as a separate PR. Check out the demo site, https://react-redux-grid.herokuapp.com. 

Let me know what you think!

**Comment by kkwak** [comment]
surprisingly, the linter is only picking up width changes - I've made that 120, is that ok? 
"npm run lint" didn't catch anything. (I'm using vscode at the moment) so I'm not sure what I should update! :)

like you said, select, index, checkbox editors seem common enough to warrant them. As such, I think we can get away with the simple:

```javascript
// for custom editors
column.editor = () => {  }  
// for select
column.editor = ["string"]  // or [ {name,value} ]
// for checkbox
column.editor = "checkbox" 
```
From the code you can see that column.editor just sets the 'type' of an input field.
so anything from: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input would apply.
No editor would default to 'text' type of course.

**Comment by kkwak** [comment]
the karma output is useless..
tried adding:
  devtool: 'inline-source-map'
 to karma.config.js, but other tests fail... go figure.

**Comment by bencripps** [comment]
After some thought I've decided that pulling in simple inputs is probably not the best idea for these reasons:

1. They wouldn't support all needs for developers who need simple editors for select and checkbox, and would probably be largely unused. We'd be maintaining code that probably doesn't fit into the `grid` module. 
2. Although it would be nice to say 'we support simple grid editing, out of the box', it feels like the feature would be more of checking the box than actually solving actual grid use-cases. Each `rest` api will be different, so we can't assume how data should be manipulated by these editors -- thus I think the best approach is to default to the `text` input since there is no complex mapping from `string` -> `string`.

After thinking about this for a couple of days, it allowed me to come to a couple of conclusions for grid as a whole, however.

1. We need better documentation on creating a complex editor; how it is modularized, and how it communicates to grid using the given `api`. 
2. I think we need some documentation on the editing/linting tools, and how best to submit a merge request for grid (many repos have this kind of documentation), I think I might take a look at those and come up with a subset of best practices.

Again, I appreciate the effort here, and I don't want to discourage any further PR's, but I just don't think adding editors to the grid source is the way I want to go.

**Comment by kkwak** [comment]
It's okay. I'll just cry in my corner. Don't mind me.

Joking aside, yup that sounds perfectly reasonable. It's not too much of a burden to take the selector code out (it was there before). I do want to re-iterate the two issues I listed:

1. selecting for '.react-grid-edit .react-grid-editor-wrapper input:enabled' is obviously not workable - and the console logs errors, as there is no 'input' if I customize the editor.
2. adding to the webpack.test.js: devtool: 'inline-source-map', breaks some tests - but this is absolutely needed as the broken line numbers are meaningless without it.

**Comment by bencripps** [comment]
Agreed for number 1 -- I will commit that change.

For number 2, we're already using a `sourcemap-loader`, and the output looks right to me. The `specrunner` should point to what test failed, and what like the failure occurred. Could you post a screenshot of the issue you're seeing?

**Pull request closed without merging**
