### PR TITLE
quickly build and run the demo

### PR DESCRIPTION
**Pull request by headwinds**
I'm testing your library and wanted to add a note in the README.md and provide a quick way for others to build and run your demo in the browser; just a baby step which gave me more confidence to dig deeper. 

I've added a few scripts in the package.json to:
* build the demo
* run the demo
* both build and run the demo 

Also added http-server as a dev dependency.

### CODE REVIEW

**Comment by bencripps** [comment]
@headwinds I like the changes, would you mind squashing the two commits into a single atomic commit?

**Comment by headwinds** [comment]
yes of course - done - I'm curious about your demo folder and then these [examples]( http://react-redux-grid.herokuapp.com ) 

Would it be helpful to have a **demos**  folder with sub folders for each example published on heroku so that each dev could see how they're configured? Or am I missing the folder where you put those other demos?! How do you see devs contributing new demos or augmenting existing ones?

**Comment by bencripps** [comment]
Thanks for the squash!

As of now, the demos folder only has a single grid implementation -- however, the source code for all of the examples that are hosted on the demo site are available at this repo:

https://github.com/bencripps/react-redux-grid-demo

Let me know if this helps, if you have any other thoughts. If not, I will go ahead and merge this PR.

Thanks!

**Comment by headwinds** [comment]
I like that separation - let me add that detail to the readme pointing new users to the examples repo beneath the link to it. 

Then I'll squash it again and push

**Comment by bencripps** [comment]
Merged -- awesome PR as well, thanks.

**Pull request merged**
